-- phpMyAdmin SQL Dump
-- version 4.9.5
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Sep 01, 2020 at 12:24 PM
-- Server version: 10.3.24-MariaDB-log
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `zaccordc_3d`
--

-- --------------------------------------------------------

--
-- Table structure for table `delivery_data`
--

CREATE TABLE `delivery_data` (
  `id` int(11) NOT NULL,
  `uid` int(11) DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `postal_code` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `city` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `mobile` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `date` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Table structure for table `fix_products`
--

CREATE TABLE `fix_products` (
  `id` int(11) NOT NULL,
  `url` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `img_url` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `img_showcase` varchar(1024) COLLATE utf8mb4_bin NOT NULL,
  `price` int(11) NOT NULL,
  `size` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `name` varchar(255) CHARACTER SET utf8 NOT NULL,
  `category` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `description` varchar(2048) CHARACTER SET utf8mb4 NOT NULL,
  `stl_path` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `priority` int(11) NOT NULL,
  `is_best` tinyint(1) NOT NULL DEFAULT 0,
  `date_added` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Dumping data for table `fix_products`
--

INSERT INTO `fix_products` (`id`, `url`, `img_url`, `img_showcase`, `price`, `size`, `name`, `category`, `description`, `stl_path`, `priority`, `is_best`, `date_added`) VALUES
(1, 'item/product=1', 'images/pizza7nagy.png', 'pipetato.jpg,pi1.jpg,pi2.jpg,pi3.jpg,pizza7nagy.png,pizza3.png,pizza_4.png,pizza6.png,pizza_10.png', 990, '40x7x28', 'Pizzás Papírcsipesz (8db)', 'Egyéb', 'Pizza alakú papírcsipesz rendszerezésre, mindennapos használatra.\r\nSegítségével könnyedén össze lehet fogni papírpénzt, kártyákat, papírlapokat és ehhez hasonló tárgyakat.\r\nMegfelelő választás lehet hétköznapi dolgok összefogására olyanoknak, akik szeretnék egyedien rendszerezni a dolgaikat. A csomag tartalma 8db pizzás papírcsipesz.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>40mm x 7mm x 28mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:445805\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/tosh/about\" class=\"bld\">Tosh</a> készítette. &#169; <!--DATE--> Tosh. Minden jog fenntartva.', 'pizza_clip', 100, 1, '2020-05-01 00:00:00'),
(2, 'item/product=2', 'images/csipesz.png', 'gyecsi.jpg,gy1.jpg,gy2.jpg,gy3.jpg,csipesz.png,csipesz_nagy.png,csipesz_nagy_harmonia.png,gyemantcsipesz_10.png\r\n', 1290, '58x12x25', 'Gyémántos Pénzcsipesz (6db)', 'Egyéb', 'Igényes pénzcsipesz hétköznapi tárgyak összefogására. Magas feszítésnek is ellenáll deformálódás nélkül, könnyen kezelhető. A csomag tartalma 6db gyémántos pénzcsipesz.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>58mm x 12mm x 25mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1385206\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/ysoft_be3d/about\" class=\"bld\">YSoft_be3D</a> készítette. &#169; <!--DATE--> YSoft_be3D. Minden jog fenntartva.\r\n ', 'diamond', 2, 0, '2020-05-14 00:00:00'),
(4, 'item/product=4', 'images/delfin_tarto.png', 'de3.jpg,de1.jpg,de2.jpg,delfin_tarto.png,delfin_telefontarto2.png,delfin_10.png', 1690, '50x65x15', 'Delfines Telefontartó', 'Telefontartók', 'Könnyen kezelhető delfines telefontartó. A termék állítva használandó és ebben a helyzetben állítva és fektetve is stabilan tartja a készüléket. A további stabilitás elérése érdekében ajánljuk az x1.3-as méretezést beállítani a specifikációknál.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>55mm x 65mm x 15mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1686467\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/goraering/about\" class=\"bld\">goraering</a> készítette. &#169; <!--DATE--> goraering. Minden jog fenntartva.\r\n ', 'delfin_tarto', 4, 0, '2020-05-14 00:00:00'),
(5, 'item/product=5', 'images/macska_tarto.png', 'mat3.jpg,mat1.jpg,mat2.jpg,macska_tarto.png,macska_telefontarto1.png,macska_telefontarto2.png,macska_telefontarto4.png,macska_tarto_10.png', 1990, '60x30x68 ', 'Macskás Telefontartó', 'Telefontartók', 'Könnyen kezelhető macskás telefontartó. A termék állítva használandó és ebben a helyzetben állítva és fektetve is stabilan tartja a készüléket. A további stabilitás elérése érdekében ajánljuk az x1.3-as méretezést beállítani a specifikációknál.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>65mm x 30mm x 68mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1012788\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/tinyeyes/about\" class=\"bld\">Tinyeyes</a> készítette. &#169; <!--DATE--> Tinyeyes. Minden jog fenntartva.', 'catstand', 5, 0, '2020-05-01 00:00:00'),
(10, 'item/product=10', 'images/tobballasu_tarto.png', 'v22.jpg,v21.jpg,v23.jpg,v24.jpg,tobballasu_tarto.png,kihajthato_telefontarto2.png,kihajthato_telefontarto1.png,v2mix_10.png', 2990, '90x64x25', 'Többállású Telefontartó', 'Telefontartók', 'Könnyen kezelhető többállású telefontartó. Stabil tartást biztosít a telefonnak, emellett a csúszkával a kívánt dőlésszög is egyszerűen beállítható.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>90mm x 64mm x 25mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2835254\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/wabbitguy/about\" class=\"bld\">wabbitguy</a> készítette. &#169; <!--DATE--> wabbitguy. Minden jog fenntartva.', 'Phone_Holder_V2_Mix', 7, 1, '2020-05-14 00:00:00'),
(11, 'item/product=11', 'images/cica_flex.png', 'ma1.jpg,ma2.jpg,cica_flex.png,cica_flex2.png,cica_flex1.png,macska_10.png', 1990, '134x106x13 ', 'Flexibilis Cica', 'Flexibilis Tárgyak', 'Flexibilis műanyag macska figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>134mm x 116mm x 13mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3576952\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/feketeimre/about\" class=\"bld\">feketeimre</a> készítette. &#169; <!--DATE--> feketeimre. Minden jog fenntartva.', 'flexicat_flat', 4, 1, '2020-05-01 00:00:00'),
(12, 'item/product=12', 'images/rak_flex.png', 'r.1.jpg,r.2.jpg,r.3.jpg,rak_flex.png,rak_flex2.png,rak_flex1.png,rak_10.png', 2190, '121x95x8 ', 'Flexibilis Rák', 'Flexibilis Tárgyak', 'Flexibilis műanyag rák figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>121mm x 95mm x 8mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3629031\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/edsparks/about\" class=\"bld\">EDSparks</a> készítette. &#169; <!--DATE--> EDSparks. Minden jog fenntartva.', 'Flexi_Crab', 12, 0, '2020-05-14 00:00:00'),
(13, 'item/product=13', 'images/sas_flex.png', 'sas1.jpg,sas2.jpg,sas_flex.png,sas_flex2.png,sas_flex1.png,sas_10.png', 1890, '163x90x5', 'Flexibilis Sas', 'Flexibilis Tárgyak', 'Flexibilis műanyag sas figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>163mm x 90mm x 5mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2939444\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/airwavested/about\" class=\"bld\">AirwavesTed</a> készítette. &#169; <!--DATE--> AirwavesTed. Minden jog fenntartva.', 'Articulated_Soaring_Eagle', 13, 0, '2020-05-01 00:00:00'),
(14, 'item/product=14', 'images/csontvaz_flex.png', 'cson1.jpg,cson2.jpg,csontvaz_flex.png,csontvaz_flex2.png,csontvaz_flex1.png,csontvaz_10.png', 2890, '207x101x9', 'Flexibilis Csontváz', 'Flexibilis Tárgyak', 'Flexibilis műanyag csontváz figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>207mm x 101mm x 9mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2299812\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/liang0108/about\" class=\"bld\">Liang0108</a> készítette. &#169; <!--DATE--> Liang0108. Minden jog fenntartva.', 'Skeleton', 14, 0, '2020-05-14 00:00:00'),
(15, 'item/product=15', 'images/unikornis_flex.png', 'u.1.jpg,u.2.jpg,unikornis_flex.png,unikornis_flex2.png,unikornis_flex3.png,unikornis_flex1.png', 1990, '102x79x13', 'Flexibilis Unikornis', 'Flexibilis Tárgyak', 'Flexibilis műanyag unikornis figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>102mm x 79mm x 13mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2835053\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/benchy4life/about\" class=\"bld\">Benchy4Life</a> készítette. &#169; <!--DATE--> Benchy4Life. Minden jog fenntartva.', 'Flexi-UnicornFlat', 5, 1, '2020-05-01 00:00:00'),
(16, 'item/product=16', 'images/dino_flex.png', 'tr1.jpg,tr2.jpg,tr3.jpg,dino_flex.png,dino2.png,dino1.png,trex_10.png', 1590, '81x67x13', 'Flexibilis Dinoszaurusz', 'Flexibilis Tárgyak', 'Flexibilis műanyag dinoszaurusz figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>81mm x 67mm x 13mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2738211\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/drlex/about\" class=\"bld\">DrLex</a> készítette. &#169; <!--DATE--> DrLex. Minden jog fenntartva.', 'Flexi-Rex', 16, 0, '2020-06-00 00:00:00'),
(17, 'item/product=17', 'images/vizilo_flex.png', 'vi2.jpg,vi1.jpg,vizilo_flex.png,vizilo_flex2.png,vizilo_flex1.png,vizilo_10.png', 1890, '99x50x10', 'Flexibilis Víziló', 'Flexibilis Tárgyak', 'Flexibilis műanyag víziló figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>99mm x 50mm x 10mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3811306\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/joanabos/about\" class=\"bld\">joanabos</a> készítette. &#169; <!--DATE--> joanabos. Minden jog fenntartva.', 'hippo', 17, 0, '0000-00-00 00:00:00'),
(19, 'item/product=19', 'images/raptor_flex.png', 'ra1.jpg,ra2.jpg,raptor_flex.png,raptor_flex2.png,raptor_flex1.png', 1990, '160x66x13', 'Flexibilis Raptor', 'Flexibilis Tárgyak', 'Flexibilis műanyag raptor figura mozgatható részekkel. Ideális választás lehet gyerekek számára vagy díszként a lakásba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>160mm x 66mm x 13mm</li>\r\n<li>Az illesztések mentén kis mértékben mozgatható</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2901355\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/cavedog/about\" class=\"bld\">Cavedog</a> készítette. &#169; <!--DATE--> Cavedog. Minden jog fenntartva.', 'raptor', 19, 0, '2020-06-00 00:00:00'),
(22, 'item/product=22', 'images/microsd_10.png', '0f.jpg,mi3.jpg,microsd_10.png,microsdkartya_tarolo2.png,microsdkartya_tarolo1.png', 1790, '45x45x16', 'Micro SD Kártya Tároló', 'Tartók, Rendszerezők', '11mm x 15mm x 1mm-es microSD kártyák tárolására alkalmas eszköz. Összesen 18db kártya a kapacitása, 2 sorban soronként 9db. Tökéletesen rendszerezi az adattárolókat és védelmet biztosít az potenciális sérülések ellen. A termék magában foglalja a tartót és annak fedelét is.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>45mm x 45mm x 16mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1289250\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/bgill/about\" class=\"bld\">bgill</a> készítette. &#169; <!--DATE--> bgill. Minden jog fenntartva.', 'microsdcardholderbottomv1', 21, 0, '2020-06-00 00:00:00'),
(24, 'item/product=24', 'images/rekesz_10.png', 't.t1.jpg,t.t2.jpg,t.t3.jpg,rekesz_10.png,titkostarolo_tarolo1.png,titkostarolo_tarolo2.png,titkostarolo_tarolo3.png,titoktarolo.png', 3790, '135x62x18', 'Titkos Falirekesz', 'Tartók, Rendszerezők', 'Falra szerelhető titkos falirekesz és tároló. Alapesetben elég nehezen észrevehető, hogy a tároló felső része csúsztatható és a belsejébe is lehet tenni dolgokat. A hátulján lévő 3 lyuknak köszönhetően könnyen falra rögzíthető.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>135mm x 62mm x 18mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:356676\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/tosh/about\" class=\"bld\">Tosh</a> készítette. &#169; <!--DATE--> Tosh. Minden jog fenntartva.', 'shelf_inside', 23, 1, '2020-06-00 00:00:00'),
(25, 'item/product=25', 'images/pendriwe_tarto_10.png', 'pesdtaha.jpg,pe1.jpg,pe2.jpg,pe3.jpg,pendriwe_tarto_10.png,sdkartya_tarolo2.png,sdkartya_tarolo3.png,sdkartya_tarolo1.png,pen_sd.png', 2790, '150x32x18', 'Pendrive, SD Kártya Tároló', 'Tartók, Rendszerezők', 'Kiváló univerzális rendszerezési és tárolási lehetőséget biztosít a leggyakrabban használt adathordozók számára. A termék egyidejűleg maximum 8db USB végű eszköz (pendrive, csatlakozó, stb.), 8db standard méretű SD kártya és 5db microSD kártya tárolására ad lehetőséget.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>150mm x 32mm x 18mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:952885\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/lalo_solo/about\" class=\"bld\">Lalo_Solo</a> készítette. &#169; <!--DATE--> Lalo_Solo. Minden jog fenntartva.', 'USB_Stick_SD_Card_Holder_-_8_USB', 24, 0, '2020-06-00 00:00:00'),
(29, 'item/product=29', 'images/kabel_rend1.png', 'kata.jpg,k_t2.jpg,k_t1.jpg,kabel_rend1.png,kabel_rend2.png', 890, '18x18x13', 'Kábel Menet (10db)', 'Tartók, Rendszerezők', 'Alkalmas különböző vastagságú kábelek megvezetésére. Könnyen és egyszerűen használható, a hátulján lévő tartó felületnek köszönhetően pedig a kívánt felületre ragasztható. A csomag tartalma 10db kábel menet.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>18mm x 18mm x 13mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1385206\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/ysoft_be3d/about\" class=\"bld\">YSoft_be3D</a> készítette. &#169; <!--DATE--> YSoft_be3D. Minden jog fenntartva.\r\n ', 'SmartPhone_Cable_Organizer_r1', 28, 0, '2020-06-00 00:00:00'),
(32, 'item/product=32', 'images/aaa_elem1.png', 'eltaha.jpg,aaa_1.jpg,aaa2.jpg,aaa_elem1.png,aaa_elem2.png', 990, '101x22x20', 'AAA Elemtároló', 'Szakeszközök', 'Praktikus tároló AAA típusú elemekhez. Egyszerre maximum 8db AAA elem tárolására képes, emellett egynél nagyobb darabszám rendelése esetén a termékek stabilan összeilleszthetők. Ideális választás lehet szakemberek számára, de otthon a lakásban is kiválóan használható.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>101mm x 22mm x 20mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:954557\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/jasond/about\" class=\"bld\">jasond</a> készítette. &#169; <!--DATE--> jasond. Minden jog fenntartva.\r\n ', 'AAAHolder', 30, 0, '2020-06-00 00:00:00'),
(33, 'item/product=33', 'images/aa_elem1.png', 'eltahaaaa.jpg,aa_1.jpg,aa_2.jpg,aa_elem1.png,aa_elem2.png', 990, '101x26x20', 'AA Elemtároló', 'Szakeszközök', 'Praktikus tároló AA típusú elemekhez. Egyszerre maximum 6db AA elem tárolására képes, emellett egynél nagyobb darabszám rendelése esetén a termékek stabilan összeilleszthetők. Ideális választás lehet szakemberek számára, de otthon a lakásban is kiválóan használható.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>101mm x 26mm x 20mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:954557\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/jasond/about\" class=\"bld\">jasond</a> készítette. &#169; <!--DATE--> jasond. Minden jog fenntartva.\r\n ', 'AAHolder', 31, 0, '2020-06-00 00:00:00'),
(34, 'item/product=34', 'images/9v_elem1.png', '9v.jpg,9v2.jpg,9v_elem1.png,9v_elem2.png', 990, '101x30x20 ', '9V-os Elemtároló', 'Szakeszközök', 'Praktikus tároló 9V-os elemekhez. Egyszerre maximum 3db elem tárolására képes, emellett egynél nagyobb darabszám rendelése esetén a termékek stabilan összeilleszthetők. Ideális választás lehet szakemberek számára, de otthon a lakásban is kiválóan használható.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>101mm x 30mm x 20mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:954557\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/jasond/about\" class=\"bld\">jasond</a> készítette. &#169; <!--DATE--> jasond. Minden jog fenntartva.\r\n ', '9VHolder', 32, 0, '2020-06-00 00:00:00'),
(37, 'item/product=37', 'images/illvaza.png', 'koneti.jpg,ill2.jpg,ill3.jpg,kor_negyszog_ill0.png,kor_negyszog_ill2.png,kor_negyszog_ill3.png', 4490, '130x123x50', 'Körből Négyzet Illúzió', 'Egyéb', '6db speciális formából álló alakzat, ami egy tükör előtt bizonyos állásokban valamikor köröket, valamikor pedig négyzeteket ábrázol. Az erről készült\r\n<a class=\"bld\" href=\"https://www.youtube.com/watch?time_continue=30&v=oWfFco7K9v8&feature=emb_logo\">videón</a> ez a fajta különleges viselkedés van bemutatva.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>130mm x 123mm x 50mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2747478\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/philkloppers/about\" class=\"bld\">PhilKloppers</a> készítette. &#169; <!--DATE--> PhilKloppers. Minden jog fenntartva.\r\n ', 'Sugihara_Cylinder_V4.1_Flat_Bottom', 35, 0, '2020-06-00 00:00:00'),
(38, 'item/product=38', 'images/akaszto2_furdo2.png', 'ak1.jpg,ak2.jpg,akaszto2_furdo2.png,akaszto2_furdo1.png', 990, '64x58x10', 'Törölközőszárító Akasztó (4db)', 'Fürdőszobai Kiegészítők', 'Kényelmes radiátorra szerelhető törölköző- és ruhaakasztó. Könnyen feltehető és egyszerűen mozgatható. A csomag tartalma 4db törölközőszárító akasztó.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>64mm x 58mm x 10mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2509573\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/mcusher/about\" class=\"bld\">McUsher</a> készítette. &#169; <!--DATE--> McUsher. Minden jog fenntartva.\r\n ', 'TowelHolderBathroom_B_224mm_96mm', 36, 1, '2020-06-00 00:00:00'),
(40, 'item/product=40', 'images/kinyomo_furdo2.png', 'fokikuha.jpg,fokiku.jpg,kinyomo_furdo2.png,kinyomo_furdo1.png', 690, '73x35x8', 'Fogkrémkinyomó Kulcs', 'Fürdőszobai Kiegészítők', 'Segítségével könnyen kinyomhatóvá válik a különböző tubusokban és tárolókban lévő maradék fogkrém, festék vagy kenőanyag. A terméken található hosszanti résbe kell befogatni a tubus végét, majd a kulcs-szerű részénél elkezdeni tekerni. A tetején található lyukak segítségével könnyen és kényelmesen tárolható vagy akasztható.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>73mm x 35mm x 8mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:21410\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/alany/about\" class=\"bld\">alany</a> készítette. &#169; <!--DATE--> alany. Minden jog fenntartva.', 'toothpaste-key', 38, 0, '2020-06-00 00:00:00'),
(42, 'item/product=42', 'images/vazatarto.png', 'va2.jpg,va1.jpg,vaza_ill1.png,vaza_ill2.png', 5490, '85x85x100', 'Arc-Váza Illúzió', 'Egyéb', 'Korhű viktoriánus serleg arc illúzióval. Amellett, hogy egy használható serleg, vízszintesen, egyszínű háttér előtt szemből nézve a termék két oldalán két arc rajzolódik ki szimmetrikusan.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>85mm x 85mm x 100mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1541337\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/alzibiff/about\" class=\"bld\">Alzibiff</a> készítette. &#169; <!--DATE--> Alzibiff. Minden jog fenntartva.', 'Vase', 40, 1, '2020-06-00 00:00:00'),
(43, 'item/product=43', 'images/gorbe_tarto.png', 'got3.jpg,got1.jpg,got2.jpg,gorbe_tarto.png,lebego_telefontarto2.png,lebego_telefontarto3.png,lebego_telefontarto.png', 3990, '87x56x106', 'Minimalista Telefontartó', 'Telefontartók', 'Elegáns, minimalista kinézetű telefontartó. Stabilan tartja a telefont állítva és fektetve, emelett kialakításának köszönhetően szinte minden típusú telefonnal kompatibilis.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>87mm x 56mm x 106mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1385206\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/ysoft_be3d/about\" class=\"bld\">YSoft_be3D</a> készítette. &#169; <!--DATE--> YSoft_be3D. Minden jog fenntartva.\r\n ', 'telefontarto_lebego', 3, 1, '2020-06-00 00:00:00'),
(44, 'item/product=44', 'images/konyvtarto.png', 'kt3.jpg,k.t4.jpg,k.t1.jpg,k.t2.jpg,konyvtarto.png,konyv_tarto2.png,konyv_tarto3.png,konyv_tarto.png', 3690, '120x85x135', 'Könyv, Füzet Állvány', 'Tartók, Rendszerezők', 'Nagyon hasznos és praktikus állvány füzetnek, festővászonnak, könyvnek és rengeteg más dolognak is. Stabilan tartja a kívánt tárgyat, ezzel könnyítve meg az esetleges olvasást, festést vagy bármilyen más munkát. Bármilyen téglalap alakú tárgyat meg tud tartani 4cm vastagság alatt.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>120mm x 85mm x 135mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2777595\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/blazincampfire/about\" class=\"bld\">BlazinCampfire</a> készítette. &#169; <!--DATE--> BlazinCampfire. Minden jog fenntartva.', 'Book_Holder', 6, 1, '2020-06-00 00:00:00'),
(45, 'item/product=45', 'images/kanaltarto.png', 'kataha.jpg,kata1.jpg,kata2.jpg,kanaltarto.png,kanal_tarto2.png,kanal_tarto1.png', 1490, '96x41x52', 'Kanál Állvány', 'Tartók, Rendszerezők', 'Szinusz hullám alakú kanáltartó. Megfelelő választás lehet olyanok számára akik sokat főznek vagy vannak a konyhában és nem szeretnék, hogy a kanálról az ételmaradék a pultra csöpögjön.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>96mm x 41mm x 52mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:22000\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/makinit/about\" class=\"bld\">makinit</a> készítette. &#169; <!--DATE--> makinit. Minden jog fenntartva.\r\n ', 'Sinewave_Spoon_Hold', 43, 0, '2020-06-00 00:00:00'),
(47, 'item/product=47\r\n', 'images/fagyi_tarto_10.png', 'to1.jpg,fagyi_tarto_10.png,fagylalt_tarto2.png,fagylalt_tarto3.png,fagylalt_tarto1.png,fagyitarto.png', 1890, '56x56x87', 'Fagylalt Tartó', 'Tartók, Rendszerezők', 'Praktikus és szép formatervezésű fagylalttartó. A tölcsért és a benne lévő fagylaltot meglehetősen stabilan tartja, kisebb lökésekre sem dől el. Ideális választás lehet otthonra különböző összejövetelekre vagy akár üzletekbe, éttermekbe is.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>56mm x 56mm x 87mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2864487\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/jpasternack/about\" class=\"bld\">jpasternack</a> készítette. &#169; <!--DATE--> jpasternack. Minden jog fenntartva.', 'Ice_cream_cone_holder_non-spiral', 45, 0, '2020-08-25 23:46:06'),
(49, 'item/product=49', 'images/csontvazfej.png', 'cs.f2.jpg,cs.f1.jpg,csontvazfej.png,csontvaz.kulcs2.png,csontvaz.kulcs.png', 1790, '54x74x5 ', 'Csontvázas Kulcstartó', 'Kulcstartók', 'Csontváz alakú kulcstartó. Megfelelő választás lehet Halloweenra.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>54mm x 74mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:984793\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/paulbadeuille/about\" class=\"bld\">PaulBaeuille</a> készítette. &#169; <!--DATE--> PaulBaeuille. Minden jog fenntartva.\r\n ', 'skull_keychain', 46, 0, '2020-06-00 00:00:00'),
(50, 'item/product=50', 'images/sokallasu_tarto.png', 'tote4.jpg,tote1.jpg,tote2.jpg,tote3.jpg,sokallasu_tarto.png,sokallasu_telefontarto2.png,sokallasu_telefontarto3.png,sokallasu_telefontarto1.png', 1590, '70x15x15 ', 'Telefonkitámasztó Kulcstartó', 'Telefontartók', 'Segítségével könnyen ki lehet vele támasztani a telefont, ezzel biztosan tartva az eszközt. Emellett lehetőség van 0&deg; és 90&deg; között állítani a tartó dőlésszögét, így minden betekintési szögből tükröződés nélkül lehet nézni a képernyőt. Az oldalán lévő praktikus lyuknak köszönhetően a kulcskarikára is rá lehet fűzni.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>70mm x 15mm x 15mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3886027\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/chienline/about\" class=\"bld\">Chienline</a> készítette. &#169; <!--DATE--> Chienline. Minden jog fenntartva.', 'modBodyRing', 47, 1, '2020-06-00 00:00:00'),
(51, 'item/product=51', 'images/ecsettarto_rovid_10.png', 'r.e1.jpg,r.e2.jpg,ecsettarto_rovid_10.png,ecsettarto2.png,ecsettarto1.png,ecsettarto.png', 990, '60x50x9 ', 'Ecsettartó', 'Tartók, Rendszerezők', 'Festés közbeni ecsettartó a munka megkönnyítése érdekében. Tökéletes helyet ad az éppen nem használt ecseteknek és megakadályozza az festék asztalra való lecsöpögését is. Egyszerre maximum 3 ecset tartására képes.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>60mm x 50mm x 9mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3862469\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/kerhac/about\" class=\"bld\">kerhac</a> készítette. &#169; <!--DATE--> kerhac. Minden jog fenntartva.', 'Paintbrush_Holder_-_3brushes', 48, 0, '2020-06-00 00:00:00'),
(53, 'item/product=53', 'images/gekko.png', 'ka1.jpg,ka2.jpg,ka3.jpg,gekko.png,kameleon2.png,kameleon1.png', 1590, '70x44x13', 'Gekko Kulcstartó', 'Kulcstartók', 'Gecko alakú kulcstartó. A zárt karikát formáló farkára lehet felfűzni a kulcsokat és egyéb dolgokat.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>70mm x 44mm x 13mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2208366\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/vocademy/about\" class=\"bld\">VOCADEMY</a> készítette. &#169; <!--DATE--> VOCADEMY. Minden jog fenntartva.\r\n ', 'gecko', 50, 1, '2020-06-00 00:00:00'),
(54, 'item/product=54', 'images/2dcucc.png', 'ru1.jpg,ru2.jpg,2drugo1.png,2drugo2.png', 1790, '54x74x5 ', '2D-s Rugó', 'Szakeszközök', 'Praktikus, 2D-s kör alakú rugó. Ideális lehet szakembereknek alkatrészként egy-egy speciálisabb esetben.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>54mm x 74mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:5713\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/scanlime/about\" class=\"bld\">scanlime</a> készítette. &#169; <!--DATE--> scanlime. Minden jog fenntartva.', 'spring2d', 51, 0, '2020-06-00 00:00:00'),
(55, 'item/product=55', 'images/dino1_1.png', 'd.m1.jpg,d.m2.jpg,d.m3.jpg,dino1_1.png,madar_kulcs2.png,madar_kulcs1.png', 1490, '50x65x5 ', 'Pteranodon Kulcstartó', 'Kulcstartók', '<a href=\"https://hu.wikipedia.org/wiki/Pteranodon\" class=\"bld\">Pteranodon</a> alakú kulcstartó. A tetején kialakított lyuk segítségével lehet felfűzni a kulcskarikára.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>50mm x 65mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:357808\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/fusionsolusion/about\" class=\"bld\">fusionsolusion</a> készítette. &#169; <!--DATE--> fusionsolusion. Minden jog fenntartva.\r\n ', 'dino_8bit4', 52, 0, '2020-06-00 00:00:00'),
(56, 'item/product=56', 'images/dino4.png', 'd.tu1.jpg,d.tu2.jpg,d.tu3.jpg,dino4.png,dino2_kulcs2.png,dino2_kulcs1.png', 1890, '77x51x5 ', 'Hylaeosaurus Kulcstartó', 'Kulcstartók', '<a href=\"https://hu.wikipedia.org/wiki/Hylaeosaurus\" class=\"bld\">Hylaeosaurus</a> alakú kulcstartó. A tetején kialakított lyuk segítségével lehet felfűzni a kulcskarikára.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>77mm x 51mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:357808\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/fusionsolusion/about\" class=\"bld\">fusionsolusion</a> készítette. &#169; <!--DATE--> fusionsolusion. Minden jog fenntartva.\r\n ', 'dino_8bit5', 53, 0, '2020-06-00 00:00:00'),
(57, 'item/product=57', 'images/dino3.png', 'd.sz1.jpg,d.sz2.jpg,dino3.png,dino3_kulcs2.png,dino3_kulcs1.png', 1790, '68x45x5 ', 'Triceratops Kulcstartó', 'Kulcstartók', '<a href=\"https://hu.wikipedia.org/wiki/Triceratops\" class=\"bld\">Triceratops</a> alakú kulcstartó. A tetején kialakított lyuk segítségével lehet felfűzni a kulcskarikára.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>68mm x 45mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:357808\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/fusionsolusion/about\" class=\"bld\">fusionsolusion</a> készítette. &#169; <!--DATE--> fusionsolusion. Minden jog fenntartva.\r\n ', 'dino_8bit3', 54, 0, '2020-06-00 00:00:00'),
(58, 'item/product=58', 'images/dino2_1.png', 'd.h3.jpg,d.h2.jpg,d.h1.jpg,dino2_1.png,dino4_kulcs2.png,dino4_kulcs1.png', 1390, '70x45x5 ', 'Psittacosaurus Kulcstartó', 'Kulcstartók', '<a href=\"https://hu.wikipedia.org/wiki/Psittacosaurus\" class=\"bld\">Psittacosaurus</a> alakú kulcstartó. A tetején kialakított lyuk segítségével lehet felfűzni a kulcskarikára.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>70mm x 45mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:357808\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/fusionsolusion/about\" class=\"bld\">fusionsolusion</a> készítette. &#169; <!--DATE--> fusionsolusion. Minden jog fenntartva.\r\n ', 'dino_8bit2', 55, 0, '2020-06-00 00:00:00'),
(59, 'item/product=59', 'images/dino5.png', 'd.t2.jpg,d.t1.jpg,d.t3.jpg,dino5.png,dino5_kulcs2.png,dino5_kulcs1.png', 1590, '70x37x5 ', 'Tyrannosaurus Kulcstartó', 'Kulcstartók', '<a href=\"https://hu.wikipedia.org/wiki/Tyrannosaurus\" class=\"bld\">Tyrannosaurus</a> alakú kulcstartó. A tetején kialakított lyuk segítségével lehet felfűzni a kulcskarikára.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>70mm x 37mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:357808\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/fusionsolusion/about\" class=\"bld\">fusionsolusion</a> készítette. &#169; <!--DATE--> fusionsolusion. Minden jog fenntartva.\r\n ', 'dino_8bit1', 56, 0, '2020-06-00 00:00:00'),
(60, 'item/product=60', 'images/ecsettartohosszu.png', 'h.e2.jpg,h.e1.jpg,ecsettartohosszu.png,hosszuecsettarto.png,hosszuecsettarto2.png', 1490, '40x100x9', 'Hosszú Ecsettartó', 'Praktikus', 'Festés közbeni ecsettartó a munka megkönnyítése érdekében. Tökéletes helyet ad az éppen nem használt ecseteknek és megakadályozza az festék asztalra való lecsöpögését is. Egyszerre maximum 9 ecset tartására képes.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>50mm x 65mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3862469\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/kerhac/about\" class=\"bld\">kerhac</a> készítette. &#169; <!--DATE--> kerhac. Minden jog fenntartva.', 'Paintbrush_Holder_-_long', 57, 0, '2020-06-00 00:00:00');
INSERT INTO `fix_products` (`id`, `url`, `img_url`, `img_showcase`, `price`, `size`, `name`, `category`, `description`, `stl_path`, `priority`, `is_best`, `date_added`) VALUES
(61, 'item/product=61', 'images/kilincskinyito.png', 'aj2.jpg,aj1.jpg,aj3.jpg,kilincskinyito.png,kilincsnyito2.png,kilincsnyito3.png', 1690, '74x64x7', 'COVID-19 Ajtókinyitó', 'Praktikus', 'Érintés nélküli kilincsfogó a COVID-19 járvány idejére. Mivel az érintés utáni azonnali fertőtlenítés nem mindenhol megoldható (főleg intézményekben és kórházakban), ezért az érintés nélküli kilincsfogó megfelelő választás lehet a járvány időszakában. Segítségével a kilincs megérintése nélkül nyithatjuk ki az ajtót, így óvva másokat is.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>50mm x 65mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:4224156\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/viktor_solenoid/designs\" class=\"bld\">viktor_solenoid</a> készítette. &#169; <!--DATE--> viktor_solenoid. Minden jog fenntartva.', 'Door_Opener_Double', 1, 1, '2020-06-00 00:00:00'),
(62, 'item/product=62', 'images/konyvlaptarto.png', 'kolataha.jpg,lap1.jpg,lap2.jpg,konyvlaptarto.png,konyvlaptarto1.png,konyvlaptarto2.png', 1190, '75x28x15 ', 'Egyujjas Könyvlaptartó', 'Praktikus', 'Könnyen használható egyujjas könyvlaptartó olvasáshoz. Ha te is sokat olvasol könyveket úgy, hogy csak a hüvelykujjaddal tartod a könyv lapjait az összecsukódástól, akkor ez a termék nagyban megkönnyítheti az olvasást. Egyszerűen csak dugd be a hüvelykujjad a lyukba és a két szélső toldás majd megtartja a lapokat.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>50mm x 65mm x 5mm</li>\r\n<li>A lyuk átmérője 33mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:144660\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/alohapussycat/designs\" class=\"bld\">Frank Erfurth</a> készítette. &#169; <!--DATE--> Frank Erfurth. Minden jog fenntartva.', 'bookringbasic', 59, 0, '2020-08-25 23:44:18'),
(64, 'item/product=64', 'images/osszefogo.png', 'ossz1.jpg,ossz2.jpg,osszefogo.png,osszefogo3.png,osszefogo2.png', 1090, '90x20x7 ', 'Hátizsák Pánt Összefogó ', 'Praktikus', 'Nagyszerű választás lehet laza, a vállról könnyen lecsúszó hátizsák pántok összefogására.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>50mm x 65mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3733804\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/skdzzz/about\" class=\"bld\">Skd zzz</a> készítette. &#169; <!--DATE--> Skd zzz. Minden jog fenntartva.', 'backpack-cord-clip-s-90', 61, 0, '2020-08-25 23:45:32'),
(65, 'item/product=65', 'images/cso.png', 'cso2.jpg,cejo.jpg,cso.png,cso1.png,cso2.png', 1990, '45x45x112', 'Célzóka', 'Praktikus', 'Férfiaknak szánt, hímvesszőre felhúzható eszköz. Merevedési problémákra vagy reggeli vizelési nehézségekre kiválóan használható termék. Egyszerűen csak fel kell húzni a célzókát a férfi hímvesszőre és megkezdeni a vizelést. A célzóka segít abban, hogy a vizelet ne spricceljen és fröcsögjön szét, így higénikusabbá téve a vizelési folyamatot.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>45mm x 45mm x 112mm</li>\r\n<li>A nagyobbik lyuk átmérője 40mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:3733804\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket a <a href=\"https://www.thingiverse.com/skdzzz/about\" class=\"bld\">Zaccord</a> készítette. &#169; <!--DATE--> Zaccord. Minden jog fenntartva.', 'cso_fasza', 62, 1, '2020-06-00 00:00:00'),
(69, 'item/product=69', 'images/fog_ki1.png', 'efokiha.jpg,efoki.jpg,efoki2.jpg,fog_ki2.png', 1890, '75x40x5', 'Egyszerű Fogkrémkinyomó', 'Fürdőszobai Kiegészítők', 'Segítségével könnyen kinyomhatóvá válik a különböző tubusokban és tárolókban lévő maradék fogkrém, festék vagy kenőanyag. A terméken található hosszanti résbe kell befogatni a tubus végét, majd elkezdeni húzni a fogkrémkinyomót a tubus eleje felé.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>75mm x 40mm x 5mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:867811\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/chattercoma/designs\" class=\"bld\">Chatter Coma</a> készítette. &#169; <!--DATE--> Chatter Coma. Minden jog fenntartva.\r\n ', 'fogkrem', 66, 0, '2020-06-00 00:00:00'),
(70, 'item/product=70', 'images/fog_ki_ma1.png', 'mefokiha.jpg,mefoki1.jpg,fog_ki_ma2.png', 1290, '80x34x7', 'Medvés Fogkrémkinyomó', 'Fürdőszobai Kiegészítők', 'Segítségével könnyen kinyomhatóvá válik a különböző tubusokban és tárolókban lévő maradék fogkrém, festék vagy kenőanyag. A terméken található hosszanti résbe kell befogatni a tubus végét, majd elkezdeni húzni a fogkrémkinyomót a tubus eleje felé. A medvés külső pedig barátságos hangulatot kölcsönöz a fürdőszobába.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>80mm x 34mm x 7mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:49263\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/makeplace/designs\" class=\"bld\">Makeplace</a> készítette. &#169; <!--DATE--> Makeplace. Minden jog fenntartva.\r\n ', 'Paste_Pusher_Animal_Bear', 67, 1, '2020-06-00 00:00:00'),
(71, 'item/product=71', 'images/fog_ki_me1.png', 'vifokiha.jpg,vifoki.jpg,fog_ki_me2.png', 1290, '80x34x7', 'Vízilovas Fogkrémkinyomó', 'Fürdőszobai Kiegészítők', 'Segítségével könnyen kinyomhatóvá válik a különböző tubusokban és tárolókban lévő maradék fogkrém, festék vagy kenőanyag. A terméken található hosszanti résbe kell befogatni a tubus végét, majd elkezdeni húzni a fogkrémkinyomót a tubus eleje felé. A vízilovas külső pedig barátságos hangulatot kölcsönöz a fürdőszobába.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>80mm x 34mm x 7mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:49263\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/makeplace/designs\" class=\"bld\">Makeplace</a> készítette. &#169; <!--DATE--> Makeplace. Minden jog fenntartva.\r\n ', 'Paste_Pusher_Animal_Hippo', 68, 0, '2020-06-00 00:00:00'),
(74, 'item/product=74', 'images/bittarto.png', '3cs2.jpg,3cs1.jpg,3cs3.jpg,3cs4.jpg,3cs5.jpg,b_t4.jpg,b_t1.jpg,b_t2.jpg,b_t3.jpg,csav_2.png', 1590, '20x20x30', '1/4\" Bittartó (6db)', 'Praktikus', '1/4\" bittartó. Ideális választás lehet szakembereknek vagy hobbi barkácsolóknak. A termék alkalmas a bármilyen 1/4\" méretű szabvány szerinti bit tárolására. A csomag tartalma 6db bittartó.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>20mm x 20mm x 30mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by-sa/3.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:1334432\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/terminus/designs\" class=\"bld\">Terminus</a> készítette. &#169; <!--DATE--> Terminus. Minden jog fenntartva.', 'Hex_Handle_rotated_for_printing', 71, 0, '2020-06-00 00:00:00'),
(75, 'item/product=75', 'images/masktarto.png', 'sz_t1.jpg,sz_t2.jpg,ak_ma1.png', 1190, '75x28x15 ', 'COVID-19 Szájmaszk Pánt', 'Praktikus', 'Szájmaszk pánt a COVID-19 járvány idejére. Hasznos termék lehet minden egészségügyi dolgozó vagy átlagember számára. A termék leveszi a terhet a használó füléről, így kényelmessé teszi a hosszabb ideig tartó maszkviselést is. Több fokozatban állítható a pánt, így szinte minden nagyságú és formájú fejhez illik.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>75mm x 28mm x 15mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:4249113\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/suraky/designs\" class=\"bld\">Ken Lord</a> készítette. &#169; <!--DATE--> Ken Lord. Minden jog fenntartva.', 'Surgical_Mask_Strap_Remix', 2, 1, '2020-06-00 00:00:00'),
(76, 'item/product=76', 'images/zacskocsipesz.png', 'cs_1.jpg,cs_2.jpg,csip_2.png', 1090, '90x20x7 ', 'Tasak Csipesz', 'Praktikus', 'Egyszerűen használható tasak csipesz. Kiválóan alkalmas szinte bármilyen task vagy zacskó összefogására kinyitás után. Masszív és stabil tervezésének köszönhetően vastagabb tasakokat vagy egyszerre akár egyszerre több zacskót is össze tud fogni.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>90mm x 20mm x 7mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:2335157\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket <a href=\"https://www.thingiverse.com/gordoninnovations/designs\" class=\"bld\">Tom Gordon</a> készítette. &#169; <!--DATE--> Tom Gordon. Minden jog fenntartva.', 'bag_clip', 73, 0, '2020-06-00 00:00:00'),
(77, 'item/product=77', 'images/ev_pa1.png', 'evpaha.jpg,e_t0.jpg,e_t1.jpg,e_t2.jpg,ev_pa2.png', 990, '45x45x112', 'Evőpálcika Összefogó', 'Praktikus', 'Nem ázsiai emberek számára nagy nehézséget okozhat az evőpálcikával való evés. Az evőpálcika összefogó lehetővé teszi, hogy bármilyen előzőleges gyakorlat nélkül tudjunk evőpálcikával enni. Az evőpálcikákat a két vájatba kell befogatni és ezután a tetejénél összenyomni, hogy felvegyük a falatot. Az anyag minimális rugalmasságának köszönhetően a pálcikák elengedés után visszaállnak eredeti pozíciójukba.<br><br>\r\n\r\nTulajdonságok:\r\n<ul class=\"dul\">\r\n<li>3DJAKE ecoPLA filament (környezetbarát, biológiai úton lebomló anyag)</li>\r\n<li>Környezetbarát csomagolás</li>\r\n<li>45mm x 45mm x 112mm</li>\r\n</ul>\r\n\r\nA termék szabad <a href=\"https://creativecommons.org/licenses/by/4.0/\" class=\"bld\">licensszel</a>\r\nvan forgalomban, így te is <a href=\"https://www.thingiverse.com/thing:5923\" class=\"bld\">megtekintheted</a>\r\nés kedved szerint módosíthatod.\r\nAbban az esetben, ha a szeretnéd a saját modelledet kinyomtatni használd a\r\n<a href=\"/print\" class=\"bld\">bérnyomtatás</a> funkciót.<br><br>\r\n\r\nA terméket a <a href=\"https://www.thingiverse.com/zydac/designs\" class=\"bld\">Zydac</a> készítette. &#169; <!--DATE--> Zydac. Minden jog fenntartva.', 'ChopstickTrainer', 74, 1, '2020-06-00 00:00:00');

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `id` int(11) NOT NULL,
  `uid` int(11) NOT NULL,
  `item_id` int(11) NOT NULL,
  `price` float NOT NULL,
  `rvas` enum('0.12','0.20','0.28','0.2') COLLATE utf8mb4_bin NOT NULL,
  `suruseg` enum('10','20','40','60','80') COLLATE utf8mb4_bin NOT NULL,
  `scale` enum('0.7','1','1.3','1.0') COLLATE utf8mb4_bin NOT NULL,
  `color` enum('Fekete','Fehér','Kék','Piros','Zöld','Sárga') COLLATE utf8mb4_bin NOT NULL,
  `fvas` enum('0.8','1.2','1.6','2.0','2.4','2') COLLATE utf8mb4_bin NOT NULL,
  `lit_sphere` enum('Domború','Homorú','Sima','') COLLATE utf8mb4_bin DEFAULT NULL,
  `lit_size` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `lit_fname` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `quantity` int(11) NOT NULL,
  `is_transfer` tinyint(1) NOT NULL,
  `transfer_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `is_fix_prod` tinyint(1) NOT NULL,
  `status` tinyint(1) NOT NULL DEFAULT 0,
  `shipping_price` int(11) NOT NULL,
  `cp_fname` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `is_cash_on_del` tinyint(1) NOT NULL DEFAULT 1,
  `packet_id` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `unique_id` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `same_billing_addr` tinyint(1) NOT NULL DEFAULT 1,
  `billing_name` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `billing_country` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `billing_city` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `billing_pcode` int(11) DEFAULT NULL,
  `billing_address` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `billing_compname` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `billing_comp_tax_num` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `order_time` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Table structure for table `packet_points`
--

CREATE TABLE `packet_points` (
  `id` int(11) NOT NULL,
  `packet_id` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `zipcode` int(11) NOT NULL,
  `city` varchar(255) NOT NULL,
  `contact` varchar(255) DEFAULT NULL,
  `phone` varchar(255) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `lat` varchar(255) DEFAULT NULL,
  `lon` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(11) NOT NULL,
  `email` varchar(320) COLLATE utf8mb4_bin NOT NULL,
  `password` varchar(512) COLLATE utf8mb4_bin NOT NULL,
  `temp_password` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `user_agent` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `ip_addr` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `register_time` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `delivery_data`
--
ALTER TABLE `delivery_data`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `fix_products`
--
ALTER TABLE `fix_products`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `packet_points`
--
ALTER TABLE `packet_points`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `delivery_data`
--
ALTER TABLE `delivery_data`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=26;

--
-- AUTO_INCREMENT for table `fix_products`
--
ALTER TABLE `fix_products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=79;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=52;

--
-- AUTO_INCREMENT for table `packet_points`
--
ALTER TABLE `packet_points`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
